# Generated by Django 4.1.3 on 2022-12-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDeployRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('deploy_type', models.CharField(max_length=20)),
                ('cluster_name', models.CharField(max_length=100)),
                ('cluster_url', models.TextField()),
                ('cluster_token', models.TextField()),
                ('namespace', models.CharField(max_length=100)),
                ('deployment', models.CharField(max_length=100)),
                ('new_deployment', models.CharField(max_length=100, null=True)),
                ('container', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('before_color', models.CharField(max_length=10, null=True)),
                ('change_color', models.CharField(max_length=10, null=True)),
                ('target_service', models.CharField(max_length=100, null=True)),
                ('before_replicas', models.CharField(max_length=10, null=True)),
                ('step', models.CharField(max_length=30)),
                ('canary_sterategy', models.CharField(max_length=100, null=True)),
                ('insert_user', models.CharField(max_length=100)),
                ('insert_at', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('app_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='APP 이름')),
                ('auto_create_ns', models.BooleanField(default=False, verbose_name='네임스페이스 생성')),
                ('namespace', models.CharField(max_length=100, verbose_name='네임스페이스')),
                ('repo_url', models.CharField(max_length=200, verbose_name='레파지토리 주소')),
                ('target_revision', models.CharField(max_length=100, verbose_name='타겟 브랜치')),
                ('target_path', models.CharField(max_length=100, verbose_name='레파지토리 경로')),
                ('insert_user', models.CharField(max_length=100)),
                ('insert_at', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CananryDeployHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appdeployrevision_id', models.IntegerField()),
                ('sterategy', models.CharField(max_length=100)),
                ('step', models.CharField(max_length=10)),
                ('Percentage', models.CharField(max_length=3)),
                ('timewait', models.IntegerField()),
                ('real_percentage', models.CharField(max_length=3, null=True)),
                ('pre_replicaset', models.IntegerField(null=True)),
                ('new_replicaset', models.IntegerField(null=True)),
                ('auto_deploy_time', models.DateTimeField(null=True)),
                ('complete_yn', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanaryStategyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sterategy', models.CharField(max_length=100)),
                ('step', models.CharField(max_length=10)),
                ('Percentage', models.CharField(max_length=3)),
                ('timewait', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='클러스터 이름')),
                ('cluster_type', models.CharField(max_length=20)),
                ('kubeconfig', models.FileField(null=True, upload_to='', verbose_name='kubeconfig 파일')),
                ('cluster_url', models.TextField()),
                ('user_id', models.CharField(max_length=100)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('bearer_token', models.TextField(verbose_name='쿠버네티스 계정 토큰')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_type', models.CharField(choices=[('RollingUpdate', '롤링 업데이트 배포'), ('BlueGreen', '블루그린 배포'), ('Canary', '카나리 배포')], default='RollingUpdate', max_length=20)),
                ('cluster_name', models.CharField(max_length=100)),
                ('cluster_url', models.TextField()),
                ('cluster_token', models.TextField()),
                ('namespace', models.CharField(max_length=100)),
                ('deployment', models.CharField(max_length=100)),
                ('container', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('before_color', models.CharField(max_length=10, null=True)),
                ('change_color', models.CharField(max_length=10, null=True)),
                ('target_service', models.CharField(max_length=100, null=True)),
                ('step', models.CharField(max_length=30)),
                ('insert_user', models.CharField(max_length=100)),
                ('insert_at', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('schedule_dt', models.DateField()),
                ('manager_user', models.CharField(max_length=100)),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.appinfo')),
            ],
        ),
        migrations.AddField(
            model_name='appinfo',
            name='cluster_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cluster', verbose_name='클러스터 이름'),
        ),
        migrations.CreateModel(
            name='AppDeployHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=100)),
                ('deploy_type', models.CharField(choices=[('RollingUpdate', '롤링 업데이트 배포'), ('BlueGreen', '블루그린 배포'), ('Canary', '카나리 배포')], default='RollingUpdate', max_length=20)),
                ('user', models.CharField(max_length=100)),
                ('namespace', models.CharField(blank=True, max_length=100)),
                ('deployment', models.CharField(blank=True, max_length=100)),
                ('container', models.CharField(blank=True, max_length=100)),
                ('step', models.CharField(max_length=30)),
                ('manager_user', models.CharField(max_length=100)),
                ('insert_at', models.DateTimeField(auto_now_add=True)),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.appinfo')),
            ],
        ),
    ]
