# Generated by Django 4.1.3 on 2022-12-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoJob',
            fields=[
                ('id', models.CharField(help_text='Unique id for this job.', max_length=255, primary_key=True, serialize=False)),
                ('next_run_time', models.DateTimeField(blank=True, db_index=True, help_text='Date and time at which this job is scheduled to be executed next.', null=True)),
                ('deploy_type', models.CharField(choices=[('RollingUpdate', '롤링 업데이트 배포'), ('BlueGreen', '블루그린 배포'), ('Canary', '카나리 배포')], default='RollingUpdate', max_length=20)),
                ('app_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.appinfo')),
            ],
            options={
                'ordering': ('next_run_time',),
            },
        ),
        migrations.CreateModel(
            name='DjangoJobExecution',
            fields=[
                ('id', models.BigAutoField(help_text='Unique ID for this job execution.', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Started execution', 'Started execution'), ('Error!', 'Error!'), ('Executed', 'Executed')], help_text='The current status of this job execution.', max_length=50)),
                ('run_time', models.DateTimeField(db_index=True, help_text='Date and time at which this job was executed.')),
                ('duration', models.DecimalField(decimal_places=2, default=None, help_text='Total run time of this job (in seconds).', max_digits=15, null=True)),
                ('finished', models.DecimalField(decimal_places=2, default=None, help_text='Timestamp at which this job was finished.', max_digits=15, null=True)),
                ('job', models.ForeignKey(help_text='The job that this execution relates to.', on_delete=django.db.models.deletion.CASCADE, to='scheduler.djangojob')),
            ],
            options={
                'ordering': ('-run_time',),
            },
        ),
    ]
